### ISSUE TITLE
Explanation for the example workflow file in the readme?

### ISSUE THREAD

**Issue by melink14** [SamuelCabralCruz/unresolved-review-threads#63]
As I was reviewing your action, I was curious about the event triggers you chose:

```
  pull_request_review_comment:
    types: [edited, deleted]

  pull_request_review:
    types: [submitted, edited, dismissed]

  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize, review_requested, review_request_removed]
    branches:
      - main
```

- `pull_request_review_comment`: Why not check `created` as well? Can editing change the resolution of a comment?
- `pull_request_review`: I submitting and dismissing will cover the bulk comments that come with review (I assume all review comments disappear after dismissing a review). Is `edited` useful?
- `pull_request`: Is there any need to have anything except `opened`, `labeled`, `unlabled` here to get the initial status?

It seems maybe we're being over eager in target choices just to have more chances to get a status update without the user having to remove the label themselves? That makes sense though might increase check latency. I wonder how it feels in practice.

Either way, it seems good to update the readme with the reasons since it's after reading your rather good write up I wasn't quite sure how all the event targets were related other than as mentioned above!

Cheers!
